version: '3'

services:
  db:
    image: mysql:8.2
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - default
    ports:
      - '53306:3306'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=NO_ENGINE_SUBSTITUTION
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - default
