version: '3'

services:
  db:
    image: postgres:16.1
    platform: linux/x86_64
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'metaboatrace_development'
    networks:
      - default
    ports:
      - '55432:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - default
