[project]
name = "crawlers"
version = "0.1.0"
description = "Crawlers for Japanese boatrace websites"
authors = [
    { name = "k0kishima", email = "okishimaxyz@gmail.com" }
]
dependencies = [
    "metaboatrace.models>=0.0.1",
    "metaboatrace.scrapers>=1.0.1",
    "requests>=2.31.0",
    "types-requests>=2.31.0.2",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev_dependencies = []
dev-dependencies = [
    "mypy>=1.5.0",
    "black>=23.7.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_optional = true
disallow_any_generics = true
disallow_untyped_defs = true
no_implicit_optional = true
explicit_package_bases = true

[tool.black]
line-length = 100
target-version = ['py310']
